#https://github.com/chupati/farm-part-3/blob/main/docker-compose.yml
#https://blog.csdn.net/Gf19991225/article/details/121981918
#https://docs.docker.com/compose/compose-file/
#https://www.erraticbits.ca/post/2021/fastapi/

# todo COPY code=>volume mapping, it's slow in MacOS docker desktop, cache isn't effective.
# todo ws connection error in cloud server. https://it.cha138.com/wen2/show-3593816.html   should build

version: "3.9"

name: "demo-farm"

services:
  mongo:
    build:
      context: ./db
    expose:
      - 27017
    ports:
      - "27017:27017"


  fastapi:
    depends_on:
      - mongo
    build:
      context: ./backend
    expose:
      - 8000
    ports:
      - "8000:8000"
    environment:
      # access to other container network via db container name, docker network automatically DNS.
      - "DATABASE_HOST=mongo"


  react:
    restart: always
    depends_on:
      - fastapi
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      # ! when production, set it as subdomains name in reverse software.
      - "NODE_ENV=production"
      - "REACT_APP_API_HTTP=https"
      - "REACT_APP_API_PORT=443"
      - "REACT_APP_API_HOST=demo-farm-fastapi.zyzypy.com"
    ports:
      # ! Entrypoint of this whole project,
      - "3000:3000"


#networks:
#  demo-farm: